app:
  name: "items"
strings:
  ru:
    start_message: "Какой герой вас интересует? Напишите его имя. Если вы закончили, нажмите кнопку выхода"
    exit_button: "Выход"
    goodbye_message: "До свидания!"
    hero_not_found: "Герой с именем '{name}' не найден. Пожалуйста, попробуйте еще раз или нажмите 'Выход'."
    next_hero_prompt: "Какой еще герой вас интересует? Напишите его имя или нажмите кнопку выхода."