app:
  name: "welcome"
strings:
  welcome_message: |
    Добро пожаловать! Чтобы найти игроков для матча в Armello, откройте субканал "Поиск игроков".
    Там мы пишем сообщения типа "here +3", "+2": это значит, что ищут еще трех, двух игроков для партии.
    Не стесняйтесь, пишите "+" в этот канал, если вы хотите присоединиться. Но не пишите туда ничего,
    кроме единичных сообщений с плюсами: этот канал специально сделан так, чтобы на него можно было поставить уведомления.
    Не захламляйте его, чтобы не пинговать людей лишний раз.
